/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ClipboardWrapper {
    'writeTextToClipboard': (newText: string) => void;
  }
  interface ClipboardWrapperAttributes extends StencilHTMLAttributes {
    'onTextChange'?: (event: CustomEvent<string>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ClipboardWrapper': Components.ClipboardWrapper;
  }

  interface StencilIntrinsicElements {
    'clipboard-wrapper': Components.ClipboardWrapperAttributes;
  }


  interface HTMLClipboardWrapperElement extends Components.ClipboardWrapper, HTMLStencilElement {}
  var HTMLClipboardWrapperElement: {
    prototype: HTMLClipboardWrapperElement;
    new (): HTMLClipboardWrapperElement;
  };

  interface HTMLElementTagNameMap {
    'clipboard-wrapper': HTMLClipboardWrapperElement
  }

  interface ElementTagNameMap {
    'clipboard-wrapper': HTMLClipboardWrapperElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
